packages:
  - .

nodeLinker: hoisted
blockExoticSubdeps: false

allowBuilds:
  electron: true
  esbuild: true
  electron-winstaller: true
  sharp: true

patchedDependencies:
  '@electron/packager@18.4.4': patches/@electron__packager@18.4.4.patch
